[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
python_files = "test_*.py"
addopts = "--cov=./ --cov-report=xml"
testpaths = ["tests"]

[tool.coverage.run]
source = ["."]
omit = ["tests/*", "setup.py"]